name: Build Kivy APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build APK using Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_spec: buildozer.spec
          buildozer_verbose: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 加班工资计算器APK
          path: bin/*.apk
